### ISSUE TITLE
Decorate / Undecorate

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc-scope#7]
We don't have those implemented but they are marked as `complete`. I am assuming they were marked that way because we have `ToggleDecorations`. I would prefer actions like this to be marked as non-complete and then either being kept at `B` or moved to `C` if we determine that `ToggleDecorations` is enough to cover that feature.

Similar story for `Maximize` / `Unmaximize` / `ToggleMaximize` (those are not marked as `complete` though):

As we already have `ToggleMaximize`, do we want to implement `(un)Maximize` at all?
Would be easy to do, just not sure if it would provide benefits other than making labwc more compatible with existing openbox configs.

**Comment by johanmalm** [comment]
Hmm.... I think I've missed `ToggleDecorations` because the numbering is one-out from that entry onwards compared with http://openbox.org/wiki/Help:Actions

Agree with your points.

If we implement `<applications>` at some point we may wish `Decorate`/`Undecorate` and the same for maximize, so cat B might be better with a comment to that effect.

**Comment by johanmalm** [comment]
Done
